#!/usr/bin/env bash
# Shared helpers for deploy.sh and individual stage scripts.
# Source this from any script that needs to SSH into a target host.

set -euo pipefail

DEPLOY_ROOT="${DEPLOY_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"

# Color helpers (terminal-safe)
if [[ -t 1 ]]; then
  C_R='\033[31m' C_G='\033[32m' C_Y='\033[33m' C_B='\033[34m' C_END='\033[0m'
else
  C_R= C_G= C_Y= C_B= C_END=
fi
log()  { printf '%b[%s]%b %s\n' "$C_B" "${HOST_TAG:-?}" "$C_END" "$*" >&2; }
ok()   { printf '%b[%s]%b %s\n' "$C_G" "${HOST_TAG:-?}" "$C_END" "$*" >&2; }
warn() { printf '%b[%s]%b %s\n' "$C_Y" "${HOST_TAG:-?}" "$C_END" "$*" >&2; }
die()  { printf '%b[%s] FATAL:%b %s\n' "$C_R" "${HOST_TAG:-?}" "$C_END" "$*" >&2; exit 1; }

# Load env for a host. Usage: load_env ru
load_env() {
  local host="$1"
  set -a
  # shellcheck disable=SC1091
  source "$DEPLOY_ROOT/envs/all.env"
  if [[ -f "$DEPLOY_ROOT/envs/$host.env" ]]; then
    # shellcheck disable=SC1091
    source "$DEPLOY_ROOT/envs/$host.env"
  else
    die "no env for host '$host'"
  fi
  set +a
}

# Expand HOST_GROUP to list of host tags.
# Exit tags are read dynamically from envs/exits.env (generated by config2env.py).
expand_hosts() {
  local group="$1"
  local exits=""
  if [[ -f "$DEPLOY_ROOT/envs/exits.env" ]]; then
    # shellcheck disable=SC1091
    source "$DEPLOY_ROOT/envs/exits.env"
    exits="${EXIT_TAGS:-}"
  fi

  case "$group" in
    ru)      echo ru ;;
    foreign) [[ -n "$exits" ]] || die "EXIT_TAGS пустой — перезапусти ./deploy.sh"
             echo "$exits" ;;
    all)     [[ -n "$exits" ]] || die "EXIT_TAGS пустой — перезапусти ./deploy.sh"
             echo "ru $exits" ;;
    *)       # Конкретный тег — проверяем что он есть в списке экзитов
             if grep -qw -- "$group" <<<"$exits"; then
               echo "$group"
             else
               die "unknown host group: $group (доступные: ru foreign all или тег из config.yaml)"
             fi ;;
  esac
}

# Авторизация: сначала pubkey (если ~/.ssh/id_* подходит), потом пароль через
# sshpass. Это позволяет 00-bootstrap залить публичный ключ оркестратора на
# ноду и отключить парольный вход — последующие стадии пойдут по ключу.
# SSHPASS экспортируется per-call чтобы пароль не светился в `ps aux`.
#
# Host-key policy: первое подключение к ноде закрепляет её host-key в
# $DEPLOY_ROOT/.known_hosts (TOFU). При повторном деплое подмена ключа =
# отказ соединения. См. SECURITY-AUDIT-2026-06-01.md (C1).
_known_hosts="${DEPLOY_ROOT}/.known_hosts"
[[ -f "$_known_hosts" ]] || { touch "$_known_hosts"; chmod 600 "$_known_hosts"; }
_ssh_opts=(
  -o StrictHostKeyChecking=accept-new
  -o UserKnownHostsFile="$_known_hosts"
  -o LogLevel=ERROR
  -o PreferredAuthentications=publickey,password
  -o PubkeyAuthentication=yes
  -o ConnectTimeout=10
  -o ConnectionAttempts=3
  -o ServerAliveInterval=15
)

# Одно ssh-соединение на ноду вместо нового рукопожатия на каждый вызов: стадия
# на ноде - это 5-7 вызовов ssh/scp (push env, push скрипта, ожидание apt,
# запуск), по полсекунды на каждый. Master живёт 60 с после последнего вызова.
# Сбой master'а ssh_exec/push видят как rc=255 и ретраят новым соединением.
_ssh_mux_dir="/tmp/anysda-ssh-$(id -u)"
if { [[ -d "$_ssh_mux_dir" ]] || mkdir -m 700 "$_ssh_mux_dir" 2>/dev/null; } && [[ -O "$_ssh_mux_dir" ]]; then
  _ssh_opts+=(
    -o ControlMaster=auto
    -o ControlPath="$_ssh_mux_dir/%C"
    -o ControlPersist=60
  )
fi

# Run a command on the current $SSH_HOST. Args are passed to ssh.
# Ретраит транзиентные сбои соединения: у VPS-экзитов SSH иногда флапает
# (таймаут / "connection closed" / banner exchange), и один такой сбой
# посреди стадии не должен ронять весь деплой.
ssh_exec() {
  : "${SSH_PASS:?SSH_PASS не задан (перезапусти ./setup.sh)}"
  local attempt rc=0
  for attempt in 1 2 3 4 5; do
    rc=0
    SSHPASS="$SSH_PASS" sshpass -e ssh "${_ssh_opts[@]}" \
        "${SSH_USER}@${SSH_HOST}" "$@" || rc=$?
    # rc=255 — сбой самого ssh (соединение). Любой другой код — это exit
    # удалённой команды (напр. `test -f` для idempotency-штампа), отдаём как есть.
    [[ $rc -ne 255 ]] && return $rc
    [[ $attempt -lt 5 ]] && { warn "ssh ${SSH_HOST}: сбой соединения, повтор ${attempt}/4"; sleep $((attempt * 3)); }
  done
  return $rc
}

# Короткая проверка «нода пускает по ssh»: одна попытка с общим потолком
# времени, причина отказа - в stdout. ConnectTimeout ограничивает только
# TCP-коннект и ожидание баннера: если фильтр по пути пропускает их, а пакеты
# обмена ключами режет, ssh висит, а ssh_exec повторяет это 5 раз. Потолок 30 с:
# у живой, но медленной ноды коннект и баннер укладываются в ConnectTimeout=10,
# KEX и вход по паролю - в единицы секунд, остаётся запас на DNS у sshd.
# Свежее соединение без мультиплексора: зависший master не должен отвечать
# за ноду, а опции до _ssh_opts, потому что у ssh побеждает первое значение.
ssh_probe() {
  : "${SSH_PASS:?SSH_PASS не задан (перезапусти ./setup.sh)}"
  local limit="${SSH_PROBE_TIMEOUT:-30}" err rc=0
  err=$(SSHPASS="$SSH_PASS" timeout -k 5 "$limit" sshpass -e ssh \
      -o ConnectionAttempts=1 -o ControlMaster=no -o ControlPath=none \
      "${_ssh_opts[@]}" "${SSH_USER}@${SSH_HOST}" 'echo ok' 2>&1 >/dev/null) || rc=$?
  [[ $rc -eq 0 ]] && return 0
  err=$(printf '%s\n' "$err" | tr -d '\r' | sed '/^[[:space:]]*$/d' | tail -1)
  case $rc in
    124|137) echo "нет ответа за ${limit} с${err:+ ($err)}: соединение или обмен ключами ssh висит, пакеты режутся по пути" ;;
    5)       echo "неверный пароль" ;;
    6)       echo "host-key ноды не принят${err:+: $err}" ;;
    *)       echo "${err:-ssh завершился с кодом $rc}" ;;
  esac
  return 1
}

# Copy a local file/dir to the host's /tmp/anysda.
# При push'е директории сначала удаляем target — иначе scp -r кладёт src
# ВНУТРЬ существующего dst (получаем /tmp/anysda/telegram/telegram/...) и
# docker build берёт устаревший верхний файл. Файл-target смело перезаписывается.
push() {
  local src="$1" dst="${2:-}"
  local target="/tmp/anysda/$(basename "$src")"
  [[ -n "$dst" ]] && target="/tmp/anysda/$dst"
  : "${SSH_PASS:?SSH_PASS не задан (перезапусти ./setup.sh)}"
  ssh_exec "mkdir -p $(dirname "$target")"
  if [[ -d "$src" ]]; then
    ssh_exec "rm -rf '$target'"
  fi
  local attempt rc=0
  for attempt in 1 2 3 4 5; do
    rc=0
    SSHPASS="$SSH_PASS" sshpass -e scp -q "${_ssh_opts[@]}" -r \
        "$src" "${SSH_USER}@${SSH_HOST}:$target" || rc=$?
    [[ $rc -eq 0 ]] && return 0
    [[ $attempt -lt 5 ]] && { warn "scp → ${SSH_HOST}: сбой, повтор ${attempt}/4"; sleep $((attempt * 3)); }
  done
  return $rc
}
