#!/usr/bin/env bash
# Stage 26 — backup tooling on RU.
# Раскатывает /usr/local/bin/anysda-{backup,restore,backup-list}.sh
# Рендерит /etc/anysda/backup.env (chmod 600) с passphrase + S3-кредами из
# config.yaml. Опционально ставит systemd timer на ежедневный backup в 02:00 UTC.
# Запускается ТОЛЬКО на ru. На exit-нодах skip.
#
# Idempotent: повторный запуск перезаписывает скрипты+env, рестартит timer.
#
# Зависимости (apt): sqlite3 (для .backup), age + expect (шифрование с
# passphrase из env), aws-cli (только если backend: s3).

set -euo pipefail

[[ -n "${1:-}" && -f "$1" ]] && source "$1"
: "${HOST_TAG:?}"

case "$HOST_TAG" in ru) ;; *) echo "[$HOST_TAG] 26-backup is ru-only — skipping"; exit 0;; esac

# Если backup-секция в config.yaml отсутствует или enabled != true — стадия
# фактически no-op (не валит деплой, но и ничего не разворачивает).
if [[ "${BACKUP_ENABLED:-}" != "true" ]]; then
  echo "[$HOST_TAG] 26-backup: backup.enabled != true — пропуск"
  exit 0
fi

: "${BACKUP_BACKEND:?BACKUP_BACKEND не задан в env}"
: "${BACKUP_LOCAL_DIR:=/var/backups/anysda-vpn2}"
: "${BACKUP_RETENTION:=10}"
: "${BACKUP_SCHEDULE:=off}"
: "${BACKUP_PASSPHRASE:?BACKUP_PASSPHRASE пуст — заполни setup.sh или backup.passphrase в config.yaml}"

STAMP_DIR=/var/anysda/.stamps
STAGE='26-backup'

mkdir -p "$STAMP_DIR" /etc/anysda "$BACKUP_LOCAL_DIR" "$BACKUP_LOCAL_DIR/.pre-restore"
chmod 700 "$BACKUP_LOCAL_DIR" "$BACKUP_LOCAL_DIR/.pre-restore"

# ── 1. Apt deps: age + expect + sqlite3 (+ aws-cli если s3) ────────────────
echo "[$HOST_TAG] [1/4] apt deps (age, expect, sqlite3$([[ "$BACKUP_BACKEND" == "s3" ]] && echo ', awscli'))"
APT_PKGS="age expect sqlite3"
[[ "$BACKUP_BACKEND" == "s3" ]] && APT_PKGS="$APT_PKGS awscli"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
# shellcheck disable=SC2086
apt-get install -y -qq $APT_PKGS >/dev/null

# ── 2. Раскатываем скрипты (push'нуты из infra/lib/ оркестратором) ──────────
echo "[$HOST_TAG] [2/4] /usr/local/bin/anysda-{backup,restore,backup-list}.sh"
install -m 0755 /tmp/anysda/anysda-backup.sh      /usr/local/bin/anysda-backup.sh
install -m 0755 /tmp/anysda/anysda-restore.sh     /usr/local/bin/anysda-restore.sh
install -m 0755 /tmp/anysda/anysda-backup-list.sh /usr/local/bin/anysda-backup-list.sh

# ── 3. /etc/anysda/backup.env — единственное место где passphrase живёт на ─
#    entry. chmod 600, root:root.
echo "[$HOST_TAG] [3/4] /etc/anysda/backup.env"
cat > /etc/anysda/backup.env <<EOF
# Generated by stage 26-backup. НЕ редактировать вручную — перезаписывается
# на каждом ./deploy.sh 26-backup ru. Источник истины — config.yaml на
# оркестраторе.
BACKUP_BACKEND='$BACKUP_BACKEND'
BACKUP_LOCAL_DIR='$BACKUP_LOCAL_DIR'
BACKUP_RETENTION='$BACKUP_RETENTION'
ANYSDA_BACKUP_PASSPHRASE='$(printf '%s' "$BACKUP_PASSPHRASE" | sed "s/'/'\\\\''/g")'
EOF

if [[ "$BACKUP_BACKEND" == "s3" ]]; then
  : "${BACKUP_S3_ENDPOINT:?BACKUP_S3_ENDPOINT не задан}"
  : "${BACKUP_S3_BUCKET:?BACKUP_S3_BUCKET не задан}"
  : "${BACKUP_S3_ACCESS_KEY:?BACKUP_S3_ACCESS_KEY не задан}"
  : "${BACKUP_S3_SECRET_KEY:?BACKUP_S3_SECRET_KEY не задан}"
  cat >> /etc/anysda/backup.env <<EOF
BACKUP_S3_ENDPOINT='$BACKUP_S3_ENDPOINT'
BACKUP_S3_BUCKET='$BACKUP_S3_BUCKET'
ANYSDA_S3_ACCESS_KEY='$(printf '%s' "$BACKUP_S3_ACCESS_KEY" | sed "s/'/'\\\\''/g")'
ANYSDA_S3_SECRET_KEY='$(printf '%s' "$BACKUP_S3_SECRET_KEY" | sed "s/'/'\\\\''/g")'
EOF
fi
chmod 600 /etc/anysda/backup.env

# ── 4. Systemd timer (только если schedule: daily) ──────────────────────────
echo "[$HOST_TAG] [4/4] systemd (schedule=$BACKUP_SCHEDULE)"
cat > /etc/systemd/system/anysda-backup.service <<'EOF'
[Unit]
Description=anysda-vpn2 — encrypted DB+secrets backup
Wants=anysda-vpn2.target

[Service]
Type=oneshot
EnvironmentFile=/etc/anysda/backup.env
ExecStart=/usr/local/bin/anysda-backup.sh
# Логи приходят в journalctl -u anysda-backup
StandardOutput=journal
StandardError=journal
EOF

cat > /etc/systemd/system/anysda-backup.timer <<'EOF'
[Unit]
Description=Daily anysda-vpn2 backup at 02:00 UTC

[Timer]
OnCalendar=*-*-* 02:00:00 UTC
Persistent=true
Unit=anysda-backup.service
RandomizedDelaySec=300

[Install]
WantedBy=timers.target
EOF

systemctl daemon-reload
if [[ "$BACKUP_SCHEDULE" == "daily" ]]; then
  systemctl enable --now anysda-backup.timer >/dev/null 2>&1
  echo "[$HOST_TAG]   timer enabled, next run:"
  systemctl list-timers anysda-backup.timer --no-pager 2>/dev/null \
    | grep -v '^$' | head -3 | sed "s/^/[$HOST_TAG]   /" || true
else
  systemctl disable --now anysda-backup.timer >/dev/null 2>&1 || true
  echo "[$HOST_TAG]   timer disabled (schedule: off)"
fi

mkdir -p "$STAMP_DIR"
touch "$STAMP_DIR/$STAGE"
echo "[$HOST_TAG] $STAGE done — try /usr/local/bin/anysda-backup.sh"
